# Generated by Django 5.0.1 on 2024-03-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fproduct', '0002_alter_finishs_amount'),
        ('products_production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_production',
            options={'verbose_name': 'Product production', 'verbose_name_plural': 'Products production'},
        ),
        migrations.AlterField(
            model_name='product_production',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product_production',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='product_production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_production', to='fproduct.finishs', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product_production',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
