# Generated by Django 5.0.1 on 2024-04-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_production', '0003_alter_product_production_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_production',
            options={'verbose_name': 'Product production'},
        ),
    ]
