# Generated by Django 5.0.1 on 2024-04-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salary'),
        ('fproduct', '0002_alter_finishs_amount'),
        ('products_production', '0004_alter_product_production_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_production',
            options={'verbose_name': 'Product production', 'verbose_name_plural': 'Products production'},
        ),
        migrations.AlterField(
            model_name='product_production',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_products', to='employees.employees', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='product_production',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='fproduct.finishs', verbose_name='Product'),
        ),
    ]
