# Generated by Django 5.0.1 on 2024-04-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_production', '0005_alter_product_production_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_production',
            options={},
        ),
        migrations.AlterModelTable(
            name='product_production',
            table='product_production',
        ),
    ]
