# Generated by Django 5.0.1 on 2024-02-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('fproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees_product_sale', to='employees.employees', verbose_name='Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sale', to='fproduct.finishs', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sales of product',
                'verbose_name_plural': 'Product sales',
            },
        ),
    ]
