# Generated by Django 5.0.1 on 2024-02-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fproduct', '0002_alter_finishs_amount'),
        ('products_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='fproduct.finishs', verbose_name='Product'),
        ),
    ]
