# Generated by Django 5.0.1 on 2024-04-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_salary'),
        ('products_sale', '0002_alter_product_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sale',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='employees.employees', verbose_name='Employee'),
        ),
    ]
