# Generated by Django 5.0.1 on 2024-04-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_sale', '0003_alter_product_sale_employees'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_sale',
            table='product_sale',
        ),
    ]
