# Generated by Django 5.0.1 on 2024-01-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(db_column='Full_Name', max_length=255)),
                ('Salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=19)),
                ('Address', models.CharField(db_column='Address', max_length=255)),
                ('Phone', models.CharField(db_column='Phone', max_length=15)),
                ('Position', models.ForeignKey(db_column='Position', on_delete=django.db.models.deletion.CASCADE, to='positions.positions')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
    ]
