# Generated by Django 5.0.1 on 2024-03-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('procurements', models.PositiveIntegerField(verbose_name='Quantity of purchases')),
                ('productions', models.PositiveIntegerField(verbose_name='Quantity of productions')),
                ('sales', models.PositiveIntegerField(verbose_name='Quantity of sales')),
                ('common', models.PositiveIntegerField(verbose_name='Total number of participations')),
                ('bonus', models.FloatField(verbose_name='Bonus')),
                ('general', models.PositiveIntegerField(verbose_name='To issue')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Issued')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.employees', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'unique_together': {('year', 'month', 'employee')},
            },
        ),
    ]
