# Generated by Django 5.0.1 on 2024-01-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Quantity', models.FloatField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Unit_id', models.ForeignKey(db_column='Unit_id', on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
            ],
            options={
                'db_table': 'FProducts',
            },
        ),
    ]
