# Generated by Django 5.0.1 on 2024-02-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Date', models.DateField()),
                ('Employee_id', models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('RawMaterial_id', models.ForeignKey(db_column='RawMaterial_id', on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterials')),
            ],
            options={
                'db_table': 'RawMaterialPurchase',
            },
        ),
    ]
