# Generated by Django 5.0.1 on 2024-02-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('raw_sale', '0001_initial'),
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Sum of budget')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='RawSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_sales', to='employees.employees', verbose_name='Employees')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_sales', to='rawmaterials.rawmaterials', verbose_name='Raw Materials')),
            ],
            options={
                'verbose_name': 'Raw Sale',
                'verbose_name_plural': 'Raw Sales',
            },
        ),
        migrations.DeleteModel(
            name='RawMaterialPurchase',
        ),
    ]
