# Generated by Django 5.0.1 on 2024-02-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_sale', '0002_budget_rawsale_delete_rawmaterialpurchase'),
        ('rawmaterials', '0002_alter_rawmaterials_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='quantity',
            field=models.FloatField(verbose_name='Amount of budget'),
        ),
        migrations.AlterField(
            model_name='rawsale',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sales', to='rawmaterials.rawmaterials', verbose_name='Raw Materials'),
        ),
    ]
