# Generated by Django 5.0.1 on 2024-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_sale', '0003_alter_budget_quantity_alter_rawsale_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='percentage',
            field=models.FloatField(default=0, verbose_name='Persent'),
        ),
    ]
