# Generated by Django 5.0.1 on 2024-04-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_sale', '0005_alter_rawsale_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawsale',
            options={'verbose_name': 'Raw Sale'},
        ),
    ]
