# Generated by Django 5.0.1 on 2024-04-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_sale', '0006_alter_rawsale_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rawsale',
            table='raw_sale',
        ),
    ]
