# Generated by Django 5.0.1 on 2024-01-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fproduct', '0001_initial'),
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('Product_id', models.ForeignKey(db_column='Product_id', on_delete=django.db.models.deletion.CASCADE, to='fproduct.finishs')),
                ('RawMaterial_id', models.ForeignKey(db_column='RawMaterial_id', on_delete=django.db.models.deletion.CASCADE, to='rawmaterials.rawmaterials')),
            ],
            options={
                'db_table': 'Ingredients',
            },
        ),
    ]
