# Generated by Django 5.0.1 on 2024-01-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fproduct', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('Product_id', 'RawMaterial_id')},
        ),
    ]
