# Generated by Django 5.0.1 on 2024-04-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredients_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together=set(),
        ),
    ]
