# Generated by Django 5.0.1 on 2024-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials',
            name='Amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
