# Generated by Django 5.0.1 on 2024-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(verbose_name='Бюджет')),
                ('percent', models.FloatField(verbose_name='Наценка')),
            ],
            options={
                'verbose_name': 'Бюджет',
            },
        ),
    ]
