# Generated by Django 5.0.1 on 2024-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='bonus',
            field=models.PositiveSmallIntegerField(verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.FloatField(verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='percent',
            field=models.FloatField(verbose_name='Extra_charge'),
        ),
    ]
