# Generated by Django 5.0.1 on 2024-04-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_options_alter_budget_bonus_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='budget',
        ),
    ]
